### ISSUE TITLE
문제 풀다가 모르는 것이 있거나 같이 고민해봤으면 하는 주제가 있으면 여기에 issue로 남겨주세요!

### ISSUE THREAD

**Issue by fingersdanny** [Kernel360-cell1/algorithm-study#8]
@Hju95 @yoonseon12 @yejincode @GBGreenBravo

**Comment by Hju95** [comment]
저의 2주차 문제에서 확장 질문 입니다.
[문제]
https://school.programmers.co.kr/learn/courses/30/lessons/42885

[질문]
최대 2명이라는 조건이 없을 경우 어떻게 풀어야하는지 모르겠습니다.
ex)
[30,30,30,30,50,70] 의 몸무게인 사람들이 있고 limit 이 120 일 때
총 보트의 수는 2로 나와야하는데 감이 잡히질 않습니다.
