### ISSUE TITLE
4주차는 불길하니까 5주차부터 다시 시작한거에요. 이번주에 드린거 6주차로 올리세요.

### ISSUE THREAD

**Issue by fingersdanny** [Kernel360-cell1/algorithm-study#97]
제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요? 제발 문제 좀 풀어,, 코테 하기 싫어..요?

**Comment by kkkapuq** [comment]
구경하러 왔다가 광기 느끼고감 ㄷㄷ

**Comment by fingersdanny** [comment]
저희 스터디원들이 코테를 풀 수 밖에 없는 이유.yml @kkkapuq
